### ISSUE TITLE
Error presenting challenge: the server could not find the requested resource (post dnspod.acme.XXX.com)

### ISSUE THREAD

**Issue by zhijunio** [kaelzhang/cert-manager-webhook-dnspod#1]
kubectl describe Challenge的时候，出现：
```
Error presenting challenge: the server could not find the requested resource (post dnspod.acme.javachen.xyz)
```
不知道你有没有遇到？

**Comment by zhijunio** [comment]
之前是没问题的，后来不知道我改了什么还是什么原因，使用你这个chart，我测试了，不会出现上面的问题。
可能是镜像问题？

**Comment by kaelzhang** [comment]
cert-manager 升级到 0.12.0 以后，各种没有更新说明。我之前用的是 0.8.0 是没问题的，手贱升级了 0.12.0，想想把它弄好把……

结果折腾了今天一天了。实在不行我今天就先退回去了。

**Comment by zhijunio** [comment]
> cert-manager 升级到 0.12.0 以后，各种没有更新说明。我之前用的是 0.8.0 是没问题的，手贱升级了 0.12.0，想想把它弄好把……
> 
> 结果折腾了今天一天了。实在不行我今天就先退回去了。

我升级到了0.12.0，都弄好了

**Comment by kaelzhang** [comment]
你遇到这个问题了吗 https://github.com/jetstack/cert-manager/issues/2111#issuecomment-570372483

不过有可能是 kube 1.14 的问题

**Comment by zhijunio** [comment]
> 你遇到这个问题了吗 [jetstack/cert-manager#2111 (comment)](https://github.com/jetstack/cert-manager/issues/2111#issuecomment-570372483)
> 
> 不过有可能是 kube 1.14 的问题

1.16.2也是空的

**Comment by iyuq** [comment]
所以这个问题解决了不？
