### ISSUE TITLE
Error presenting challenge: secrets "dnspod-credentials" is forbidden: User "system:serviceaccount:cert-manager:cert-manager-webhook-dnspod" cannot get resource "secrets" in API group "" in the namespace "cert-manager"

### ISSUE THREAD

**Issue by zhijunio** [kaelzhang/cert-manager-webhook-dnspod#3]
Error presenting challenge: secrets "dnspod-credentials" is forbidden: User "system:serviceaccount:cert-manager:cert-manager-webhook-dnspod" cannot get resource "secrets" in API group "" in the namespace "cert-manager"

没有为dnspod-credentials创建RBAC，会提示上面的异常信息

**Comment by kaelzhang** [comment]
Sorry, this repo is still working in progress. I'll inform you once it's ready
